# Write your code here :-)
print('Enter the name of cat1:')
cat1=input()
print('Enter the name of cat2:')
cat2=input()
print('Enter the name of cat3:')
cat3=input()
print('Enter the name of cat4:')
cat4=input()
print('Enter the name of cat5:')
cat5=input()
print('the cat names are')
print(cat1+' '+cat2+' '+cat3+' '+cat4+' '+cat5)
